# Generated by Django 4.1.5 on 2023-01-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_article_created_article_updated_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='genre',
            field=models.CharField(choices=[('education', 'Education'), ('movie', 'Movie'), ('sports', 'Sports'), ('other', 'Other')], default='education', max_length=20),
        ),
    ]
